LanchesMac/Areas/Admin/Controllers/AdminGraficoController.cs
using LanchesMac.Areas.Admin.Servicos;
using Microsoft.AspNetCore.Mvc;
using System;

namespace LanchesMac.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminGraficoController : Controller
    {
        private readonly GraficoVendasService _graficoVendas;

        public AdminGraficoController(GraficoVendasService graficoVendas)
        {
            _graficoVendas = graficoVendas ?? throw
                new ArgumentNullException(nameof(graficoVendas));
        }

        public JsonResult VendasLanches(int dias)
        {
            var lanchesVendasTotais = _graficoVendas.GetVendasLanches(dias);
            return Json(lanchesVendasTotais);
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult VendasMensal()
        {
            return View();
        }

        [HttpGet]
        public IActionResult VendasSemanal()
        {
            return View();
        }
    }
}
    

LanchesMac/Areas/Admin/Views/AdminGrafico/Index.cshtml
<title>
    @ViewData["Title"] - Grafico de Vendas
</title>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<div id="chart_div" style="width: 900px; height: 500px;"></div>

<script type="text/javascript">

    google.charts.load('current', {packages: ['corechart', 'bar']});
    google.charts.setOnLoadCallback(CarregaDados);

    function CarregaDados() {
        $.ajax({
            url: '@Url.Action("VendasLanches", "AdminGrafico")',
            data: {dias: 360},
            dataType: "json",
            type: "GET",
            error: function(xhr, status, error) {
                var err = eval("(" + xhr.responseText + ")");
                toastr.error(err.message);
            },
            success: function(data) {
                GraficoVendasLanches(data);
                return false;
            }
        });
        return false;
    }

    function GraficoVendasLanches(data) {
        var dataArray = [
            ['Lanche', 'Quantidade' , 'Valores(R$)']
        ];
        $.each(data, function(i, item) {
            dataArray.push([item.lancheNome, item.lanchesQuantidade, item.lanchesValorTotal]);
        });
        var data = google.visualization.arrayToDataTable(dataArray);
        var options = {
            title: 'Lanches - Vendas nos últimos 360 dias',
            chartArea: {
                width: '70%'
            },
            colors: ['#5202b5', '#d2a828'],
            hAxis: {
                title: 'Valor Total (em Reais)',
                minValue: 0
            },
            vAxis: {
                title: 'Lanches'
            }
        };
        var chart = new google.visualization.BarChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    }
</script>

LanchesMac/Areas/Admin/Views/AdminGrafico/VendasMensal.cshtml
<title>
    @ViewData["Title"] - Grafico de Vendas
</title>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<div id="chart_div" style="width: 900px; height: 500px;"></div>

<script type="text/javascript">

    google.charts.load('current', {packages: ['corechart', 'bar']});
    google.charts.setOnLoadCallback(CarregaDados);

    function CarregaDados() {
        $.ajax({
            url: '@Url.Action("VendasLanches", "AdminGrafico")',
            data: {dias: 30},
            dataType: "json",
            type: "GET",
            error: function(xhr, status, error) {
                var err = eval("(" + xhr.responseText + ")");
                toastr.error(err.message);
            },
            success: function(data) {
                GraficoVendasLanches(data);
                return false;
            }
        });
        return false;
    }

    function GraficoVendasLanches(data) {
        var dataArray = [
            ['Lanche', 'Quantidade' , 'Valores(R$)']
        ];
        $.each(data, function(i, item) {
            dataArray.push([item.lancheNome, item.lanchesQuantidade, item.lanchesValorTotal]);
        });
        var data = google.visualization.arrayToDataTable(dataArray);
        var options = {
            title: 'Lanches - Vendas nos últimos 30 dias',

            animation: {
                duration: 3000,
                easing: 'out',
                startup: true
            },

            chartArea: {
                width: '70%'
            },
            colors: ['#5202b5', '#d2a828'],
            hAxis: {
                title: 'Valor Total (em Reais)',
                minValue: 0
            },
            vAxis: {
                title: 'Lanches'
            }
        };
        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    }
</script>

LanchesMac/Areas/Admin/Views/AdminGrafico/VendasSemanal.cshtml
<title>
    @ViewData["Title"] - Grafico de Vendas
</title>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<div id="chart_div" style="width: 900px; height: 500px;"></div>

<script type="text/javascript">

    google.charts.load('current', {packages: ['corechart', 'bar']});
    google.charts.setOnLoadCallback(CarregaDados);

    function CarregaDados() {
        $.ajax({
            url: '@Url.Action("VendasLanches", "AdminGrafico")',
            data: {dias: 7},
            dataType: "json",
            type: "GET",
            error: function(xhr, status, error) {
                var err = eval("(" + xhr.responseText + ")");
                toastr.error(err.message);
            },
            success: function(data) {
                GraficoVendasLanches(data);
                return false;
            }
        });
        return false;
    }

    function GraficoVendasLanches(data) {
        var dataArray = [
            ['Lanche', 'Quantidade' , 'Valores(R$)']
        ];
        $.each(data, function(i, item) {
            dataArray.push([item.lancheNome, item.lanchesQuantidade, item.lanchesValorTotal]);
        });
        var data = google.visualization.arrayToDataTable(dataArray);
        var options = {
            title: 'Lanches - Vendas nos últimos 7 dias',

            curveType: 'function',
            legend: { position : 'bottom'},

            chartArea: {
                width: '70%'
            },
            colors: ['#5202b5', '#d2a828'],
            hAxis: {
                title: 'Valor Total (em Reais)',
                minValue: 0
            },
            vAxis: {
                title: 'Lanches'
            }
        };
        var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    }
</script>